version: 0.2

phases:
  install:
    commands:
      # kubectl 명령어를 사용할 수 있도록 설치하는 과정
      - echo "kubectl 설치 중..."
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.9/2024-01-04/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/

  pre_build:
    commands:
      # EKS 클러스터에 접속하기 위한 권한(kubeconfig) 설정
      - echo "EKS 클러스터 접속 정보 업데이트..."
      - # <클러스터_이름>을 실제 EKS 클러스터 이름으로 변경하세요.
      - aws eks update-kubeconfig --region us-east-1 --name user126-cluster

  build:
    commands:
      # 본격적인 배포(Deploy) 시작
      - echo "쿠버네티스 배포 시작..."
      
      # 중요: 이전 단계(Build)에서 넘어온 최신 이미지 태그로 deployment.yaml 내부의 이미지 주소를 치환합니다.
      # (아래 sed 명령어는 Linux 환경에서 파일 안의 특정 문자열을 찾아 바꾸는 명령어입니다.)
      - echo "매니페스트 이미지 태그 업데이트..."
      
        # 빌드 때 생성한 태그와 동일한 태그를 여기서도 똑같이 만들어냅니다)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      - # 주의: $REPOSITORY_URI 와 $IMAGE_TAG 는 CodePipeline 환경 변수로 전달받아야 합니다.
      - sed -i "s|image: .*lms-frontend:latest|image: 879772956301.dkr.ecr.us-east-1.amazonaws.com/lms-frontend:$IMAGE_TAG|g" k8s/frontend-deployment.yaml
      
      # 매니페스트 적용 (파드 생성/업데이트)
      - kubectl apply -f k8s/frontend-config.yaml
      - kubectl apply -f k8s/frontend-deployment.yaml
      - kubectl apply -f k8s/frontend-service.yaml

  post_build:
    commands:
      # 롤링 업데이트가 무사히 완료되었는지 상태를 확인하고 배포 단계를 종료합니다.
      - echo "배포 상태 검증..."
      - kubectl rollout status deployment/lms-frontend-deployment